sudo: required
dist: trusty
services: docker
language: generic

notifications:
  email:
    on_failure: always

env:
  matrix:
    - ROS_DISTRO="indigo" ROS_REPO=ros-shadow-fixed BEFORE_SCRIPT='sudo ./install_minimal_linuxcan.sh'
    - ROS_DISTRO="indigo" ROS_REPO=ros BEFORE_SCRIPT='sudo ./install_minimal_linuxcan.sh'
    - ROS_DISTRO="kinetic" ROS_REPO=ros-shadow-fixed BEFORE_SCRIPT='sudo ./install_minimal_linuxcan.sh'
    - ROS_DISTRO="kinetic" ROS_REPO=ros BEFORE_SCRIPT='sudo ./install_minimal_linuxcan.sh'

matrix:
  allow_failures:
    env: ROS_DISTRO="indigo" ROS_REPO=ros-shadow-fixed BEFORE_SCRIPT='sudo ./install_minimal_linuxcan.sh'
    env: ROS_DISTRO="kinetic" ROS_REPO=ros-shadow-fixed BEFORE_SCRIPT='sudo ./install_minimal_linuxcan.sh'

install:
  git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  source .ci_config/travis.sh
